### PR TITLE
Add `scipy` as additional visualization dependency

### PR DESCRIPTION
**Pull request by flferretti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by flferretti** [comment]
@conda-forge-admin, please rerender

**Review by diegoferigo — APPROVED** [review]
I checked more in detail and the introduction of `scipy` is much older than https://github.com/ami-iit/jaxsim/pull/206. It goes back to https://github.com/ami-iit/jaxsim/pull/83, specifically [this import](https://github.com/ami-iit/jaxsim/blob/3a968abfed433c677fee076cb7ff975e44141351/src/jaxsim/mujoco/model.py#L10).

Thanks!

**Comment by flferretti** [comment]
JAX already installs `scipy` (https://conda-metadata-app.streamlit.app/~/+/?q=conda-forge%2Fnoarch%2Fjax-0.4.28-pyhd8ed1ab_0.conda#dependencies), but I believe it is better to be on the safe side

**Comment by diegoferigo** [comment]
> JAX already installs `scipy` (https://conda-metadata-app.streamlit.app/~/+/?q=conda-forge%2Fnoarch%2Fjax-0.4.28-pyhd8ed1ab_0.conda#dependencies), but I believe it is better to be on the safe side

Even better if plain `scipy` is a direct dependency of `jax`. In any case, yep it's always reasonable to explicitly list all the direct dependencies. And the identification of such dependencies is also one of the reason of the current formatting of the imports.

**Pull request merged**
